// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyFetchedCover(arg1, arg2) {
  return window['go']['main']['App']['ApplyFetchedCover'](arg1, arg2);
}

export function DeleteBook(arg1) {
  return window['go']['main']['App']['DeleteBook'](arg1);
}

export function DetectDevices() {
  return window['go']['main']['App']['DetectDevices']();
}

export function FetchBookMetadata(arg1) {
  return window['go']['main']['App']['FetchBookMetadata'](arg1);
}

export function GetAllAuthors() {
  return window['go']['main']['App']['GetAllAuthors']();
}

export function GetAllSeries() {
  return window['go']['main']['App']['GetAllSeries']();
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetBook(arg1) {
  return window['go']['main']['App']['GetBook'](arg1);
}

export function GetBooks() {
  return window['go']['main']['App']['GetBooks']();
}

export function GetCoverData(arg1) {
  return window['go']['main']['App']['GetCoverData'](arg1);
}

export function GetDeviceFileCover(arg1) {
  return window['go']['main']['App']['GetDeviceFileCover'](arg1);
}

export function GetPreferences() {
  return window['go']['main']['App']['GetPreferences']();
}

export function ImportDir(arg1) {
  return window['go']['main']['App']['ImportDir'](arg1);
}

export function ImportFile(arg1) {
  return window['go']['main']['App']['ImportFile'](arg1);
}

export function ImportFromCalibre(arg1) {
  return window['go']['main']['App']['ImportFromCalibre'](arg1);
}

export function ListDeviceBooks(arg1) {
  return window['go']['main']['App']['ListDeviceBooks'](arg1);
}

export function RemoveFromDevice(arg1, arg2) {
  return window['go']['main']['App']['RemoveFromDevice'](arg1, arg2);
}

export function ResetLibrary() {
  return window['go']['main']['App']['ResetLibrary']();
}

export function SavePreferences(arg1) {
  return window['go']['main']['App']['SavePreferences'](arg1);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SendBook(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendBook'](arg1, arg2, arg3);
}

export function UpdateBook(arg1) {
  return window['go']['main']['App']['UpdateBook'](arg1);
}
