// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {device} from '../models';
import {fetcher} from '../models';
import {metadata} from '../models';
import {prefs} from '../models';

export function ApplyFetchedCover(arg1:number,arg2:string):Promise<string>;

export function DeleteBook(arg1:number):Promise<void>;

export function DetectDevices():Promise<Array<device.DeviceInfo>>;

export function EjectDevice(arg1:string):Promise<void>;

export function FetchBookMetadata(arg1:number):Promise<Array<fetcher.FetchedMetadata>>;

export function GetAllAuthors():Promise<Array<string>>;

export function GetAllSeries():Promise<Array<string>>;

export function GetAllTags():Promise<Array<string>>;

export function GetBook(arg1:number):Promise<metadata.Book>;

export function GetBooks():Promise<Array<metadata.Book>>;

export function GetCoverData(arg1:string):Promise<string>;

export function GetDeviceFileCover(arg1:string):Promise<string>;

export function GetPreferences():Promise<prefs.Preferences>;

export function ImportBooksFromDevice(arg1:Array<string>):Promise<number>;

export function ImportDir(arg1:string):Promise<Array<metadata.Book>>;

export function ImportFile(arg1:string):Promise<metadata.Book>;

export function ImportFromCalibre(arg1:string):Promise<Array<metadata.Book>>;

export function ListDeviceBooks(arg1:string):Promise<Array<metadata.BookFile>>;

export function OpenBook(arg1:number,arg2:string):Promise<void>;

export function RemoveFromDevice(arg1:string,arg2:Array<string>):Promise<void>;

export function ResetLibrary():Promise<void>;

export function SavePreferences(arg1:prefs.Preferences):Promise<void>;

export function Search(arg1:string):Promise<Array<metadata.Book>>;

export function SelectDirectory():Promise<string>;

export function SelectFiles():Promise<Array<string>>;

export function SendBook(arg1:number,arg2:string,arg3:metadata.Format):Promise<void>;

export function UpdateBook(arg1:metadata.Book):Promise<void>;
